/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JPanel;

/**
 *
 * @author walter
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    private Ingresar dashboard;
    private Perfil perfil;
    private Insertad insertad;
    private Verlos verlos;
    private Modificar modificar;
    public Inicio() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);// bootn cerrar
        setName("pricipalJFrame");
        setTitle("Proyecto");
        setResizable(false);
        pack(); //trar todos los subcomponentes
        setIconImage(getIconImage());
        setLocationRelativeTo(null);//mirat
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    private void iniciar() {
        dashboard = new Ingresar(this);
        dashboard.setVisible(true);
        add(dashboard);
        pack();
        setLocationRelativeTo(null);  
    }
    public void irAPerfil(JPanel jpanel){
        remove(jpanel);
        perfil = new Perfil(this);
        perfil.setVisible(true);
        add(perfil);
        pack();
        setLocationRelativeTo(null); 
    }
    public void irAInsertar(JPanel jpanel){
        remove(jpanel);
        insertad = new Insertad(this);
        insertad.setVisible(true);
        add(insertad);
        pack();
        setLocationRelativeTo(null);
    }
    public void irAVer(JPanel jpanel){
        remove(jpanel);
        verlos = new Verlos(this);
        verlos.setVisible(true);
        add(verlos);
        pack();
        setLocationRelativeTo(null); 
    }
    public void irAModificar(JPanel jpanel){
        remove(jpanel);
        modificar = new Modificar(this);
        modificar.setVisible(true);
        add(modificar);
        pack();
        setLocationRelativeTo(null); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
