/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.LogicaMascotas;
import Modelo.Mascota;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author walter
 */
public class Perfil extends javax.swing.JPanel {

    /** Creates new form Perfil */
    private Inicio inicio;
    ArrayList<Mascota> mascotas = LogicaMascotas.ver();
    private Verlos verlos = new Verlos(inicio);
    /*private LogicaMascotas mascotas = new LogicaMascotas();

    public LogicaMascotas getMascotas() {
        return mascotas;
    }

    public void setMascotas(LogicaMascotas mascotas) {
        this.mascotas = mascotas;
    }*/
    public Perfil(Inicio inicio) {
        this.inicio=inicio;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        bt_insertar = new javax.swing.JLabel();
        bt_modificar = new javax.swing.JLabel();
        bt_ver = new javax.swing.JLabel();
        bt_borrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        bt_insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/insertar1.png"))); // NOI18N
        bt_insertar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_insertarMouseMoved(evt);
            }
        });
        bt_insertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_insertarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_insertarMousePressed(evt);
            }
        });

        bt_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/modificar1.png"))); // NOI18N
        bt_modificar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_modificarMouseMoved(evt);
            }
        });
        bt_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_modificarMousePressed(evt);
            }
        });

        bt_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/ver1.png"))); // NOI18N
        bt_ver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_verMouseMoved(evt);
            }
        });
        bt_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_verMousePressed(evt);
            }
        });

        bt_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recurso/borrar.png"))); // NOI18N
        bt_borrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_borrarMouseMoved(evt);
            }
        });
        bt_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_borrarMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Que deseas hacer?");
        jLabel5.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_modificar)
                                .addGap(18, 18, 18)
                                .addComponent(bt_borrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_insertar)
                                .addGap(18, 18, 18)
                                .addComponent(bt_ver))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_insertar)
                    .addComponent(bt_ver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_borrar)
                    .addComponent(bt_modificar))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_insertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_insertarMouseClicked
        
    }//GEN-LAST:event_bt_insertarMouseClicked

    private void bt_insertarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_insertarMousePressed
        irAInsertar();
    }//GEN-LAST:event_bt_insertarMousePressed

    private void bt_insertarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_insertarMouseMoved
        bt_insertar.setToolTipText("Registra tu mascota");
    }//GEN-LAST:event_bt_insertarMouseMoved

    private void bt_verMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_verMousePressed
        irAVer();
    }//GEN-LAST:event_bt_verMousePressed

    private void bt_verMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_verMouseMoved
        bt_ver.setToolTipText("Ver tus mascotas");
    }//GEN-LAST:event_bt_verMouseMoved

    private void bt_borrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_borrarMousePressed
        if(mascotas.size()>0){
            int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Seguro deseas liberar TODAS las mascotas", "seguro?", 0, 1);
                try {
                    if(showConfirmDialog!=1)
                        borrarTodo();
                    
                }catch(Exception e){

                }
        }else{
            JOptionPane.showMessageDialog(null, "No hay mascotas que liberar", "no hay nada", 1);
        }
    }//GEN-LAST:event_bt_borrarMousePressed

    private void bt_modificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarMousePressed
        if(mascotas.size()>0){
           irAModificar();
        }else{
            JOptionPane.showMessageDialog(null, "No hay mascotas todavia", "no hay nada", 1);
        }
        
    }//GEN-LAST:event_bt_modificarMousePressed

    private void bt_modificarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarMouseMoved
        bt_modificar.setToolTipText("Modifica tus mascotas");
    }//GEN-LAST:event_bt_modificarMouseMoved

    private void bt_borrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_borrarMouseMoved
        bt_borrar.setToolTipText("Libera todas tus mascotas");
    }//GEN-LAST:event_bt_borrarMouseMoved
    public void irAInsertar(){
        inicio.irAInsertar(this);
    }
    public void irAVer(){
        inicio.irAVer(this);
    }
    public void borrar(String s){
        LogicaMascotas.borrar(s);
    }
    public void borrarTodo(){
        LogicaMascotas.borrar();
    }
    public void irAModificar(){
        inicio.irAModificar(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_borrar;
    private javax.swing.JLabel bt_insertar;
    private javax.swing.JLabel bt_modificar;
    private javax.swing.JLabel bt_ver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

}
