/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.LogicaMascotas;
import Modelo.Mascota;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author walter
 */
public class Verlos extends javax.swing.JPanel {

    /**
     * Creates new form Insertar
     */
    
    private Inicio inicio;

    ArrayList<Mascota> mascotas = LogicaMascotas.ver();
    
    
    JLabel no_disponible = new JLabel();
    private Mascota pokemon;
    private int n, cantidad =0;
    public Verlos(Inicio inicio) {
        this.inicio=inicio;
        initComponents();
        init();
        pokemo.setIcon(no_disponible.getIcon());
        ver();
    }
    private void init(){
        n=0;
        no_disponible.setIcon(new ImageIcon(getClass().getResource("/Recurso/no disponible.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        nombre = new javax.swing.JLabel();
        pokemo = new javax.swing.JLabel();
        raza = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        dueno = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();
        adelante = new javax.swing.JLabel();
        atras = new javax.swing.JLabel();
        bt_volver = new javax.swing.JButton();
        edad1 = new javax.swing.JLabel();
        raza1 = new javax.swing.JLabel();
        dueno1 = new javax.swing.JLabel();
        contacto1 = new javax.swing.JLabel();
        bt_borrar = new javax.swing.JLabel();
        posicion = new javax.swing.JLabel();

        nombre.setFont(new java.awt.Font("Ravie", 1, 12)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("(No hay mascotas todavia)");

        raza.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        raza.setText("N/A");

        edad.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        edad.setText("N/A");

        dueno.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        dueno.setText("N/A");

        contacto.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        contacto.setText("N/A");

        adelante.setForeground(new java.awt.Color(153, 153, 153));
        adelante.setText(">>");
        adelante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adelanteMousePressed(evt);
            }
        });

        atras.setForeground(new java.awt.Color(153, 153, 153));
        atras.setText("<<");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atrasMousePressed(evt);
            }
        });

        bt_volver.setText("volver");
        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });

        edad1.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        edad1.setText("Edad:");

        raza1.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        raza1.setText("Raza:");

        dueno1.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        dueno1.setText("Dueño:");

        contacto1.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        contacto1.setText("Contacto:");

        bt_borrar.setForeground(new java.awt.Color(153, 153, 153));
        bt_borrar.setText("Retirarlo");
        bt_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_borrarMousePressed(evt);
            }
        });

        posicion.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_borrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(adelante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addComponent(pokemo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raza, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dueno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raza1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dueno1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_volver))
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(pokemo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adelante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(raza1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(raza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(dueno1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(dueno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_volver)
                        .addGap(18, 18, 18)
                        .addComponent(bt_borrar)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        volver();
    }//GEN-LAST:event_bt_volverActionPerformed

    private void adelanteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adelanteMousePressed
        vermas();
    }//GEN-LAST:event_adelanteMousePressed

    private void atrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMousePressed
        vermenos();
    }//GEN-LAST:event_atrasMousePressed

    private void bt_borrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_borrarMousePressed
        if(mascotas.size()>0){
            int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Seguro deseas retirar tu mascota?", "seguro?", 0, 1);
            try {
                if(showConfirmDialog!=1)
                    borrar(pokemon.getNombreMascota());
                
                if(mascotas.size()>0){
                    n=0;
                    ver();
                }else if(mascotas.size()==0){
                    nombre.setText("(No hay mascotas todavia)");
                    edad.setText("N/A");
                    raza.setText("N/A");
                    dueno.setText("N/A");
                    contacto.setText("N/A");
                    posicion.setText("");
                    pokemo.setIcon(no_disponible.getIcon());
                }
                    
            } catch (IOException ex) {
                Logger.getLogger(Verlos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_bt_borrarMousePressed
    public void volver(){
        inicio.irAPerfil(this);
    }
    public void ver(){  
        
        if(mascotas.size()>0){
            int x =(int) (Math.random()*10);
            pokemon = mascotas.get(n);
            bt_borrar.setForeground(Color.BLACK);
            nombre.setText(pokemon.getNombreMascota());
            edad.setText(pokemon.getEdad());
            raza.setText(pokemon.getRaza());
            dueno.setText(pokemon.getNombreDueño());
            contacto.setText(pokemon.getCelular());
            posicion.setText(n+1+"");
            pokemo.setIcon(mascotas.get(n).getIcon());
            if(mascotas.size()>1){
                adelante.setForeground(Color.BLACK);
            }     
        }
    }
    public void vermas(){
        if(mascotas.size()>1 && pokemon!=mascotas.get(mascotas.size()-1)){
            n++;
            atras.setForeground(Color.BLACK);
            ver();
            if(n==mascotas.size()-1)
                adelante.setForeground(Color.GRAY);
        }else{
            adelante.setForeground(Color.GRAY);
        }
    }
    public void vermenos(){
        if(mascotas.size()>1 && pokemon!=mascotas.get(0)){
            n--;
            adelante.setForeground(Color.BLACK);
            ver();
            if(n==0){
                atras.setForeground(Color.GRAY);
            }
        }
        else{
            atras.setForeground(Color.GRAY);
        }
    }
    public void borrar(String s) throws IOException{
        LogicaMascotas.borrar(s);
        cantidad--;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adelante;
    private javax.swing.JLabel atras;
    private javax.swing.JLabel bt_borrar;
    private javax.swing.JButton bt_volver;
    private javax.swing.JLabel contacto;
    private javax.swing.JLabel contacto1;
    private javax.swing.JLabel dueno;
    private javax.swing.JLabel dueno1;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel edad1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel pokemo;
    private javax.swing.JLabel posicion;
    private javax.swing.JLabel raza;
    private javax.swing.JLabel raza1;
    // End of variables declaration//GEN-END:variables
}
