/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaAdmin;

import Controlador.LogicaUsuario;
import Modelo.Conexion;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import com.placeholder.PlaceHolder;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author walter
 */
public class CrearUsuario extends javax.swing.JPanel {

    /**
     * Creates new form CrearUsuario
     */
    private String nombre, apellido, cedula, correo, numeroContacto, apellid2, pass,repeatPass ,usuario, direccion, tipoUsuario;
    
    LogicaUsuario logica = new LogicaUsuario();
    public CrearUsuario() {
        initComponents();
        holders();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_correo = new javax.swing.JTextField();
        boton_crear = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        obligatorio = new javax.swing.JLabel();
        obligatorio1 = new javax.swing.JLabel();
        obligatorio2 = new javax.swing.JLabel();
        obligatorio4 = new javax.swing.JLabel();
        obligatorio5 = new javax.swing.JLabel();
        label_creandoUsuario = new javax.swing.JLabel();
        obligatorio6 = new javax.swing.JLabel();
        obligatorio7 = new javax.swing.JLabel();
        obligatorio8 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        ayuda = new javax.swing.JLabel();
        obligatorio3 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        txt_primerApellido = new javax.swing.JTextField();
        txt_segundoApellido = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_numeroContacto = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        txt_repetirContraseña = new javax.swing.JPasswordField();
        bx_tipo_usuario = new javax.swing.JComboBox();
        obligatorio9 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(558, 508));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 360, 31));

        boton_crear.setText("Crear");
        boton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crearActionPerformed(evt);
            }
        });
        add(boton_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 210, -1));

        boton_salir.setText("Regresar");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });
        add(boton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        obligatorio.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio.setText("*");
        add(obligatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 10, -1));

        obligatorio1.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio1.setText(" *");
        add(obligatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 10, -1));

        obligatorio2.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio2.setText(" *");
        add(obligatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 10, -1));

        obligatorio4.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio4.setText(" *");
        add(obligatorio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 10, -1));

        obligatorio5.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio5.setText("*");
        add(obligatorio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 10, -1));

        label_creandoUsuario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label_creandoUsuario.setText("Creando Usuario");
        add(label_creandoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 23));

        obligatorio6.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio6.setText("*");
        add(obligatorio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 10, -1));

        obligatorio7.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio7.setText("*");
        add(obligatorio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 20, -1));

        obligatorio8.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio8.setText("*");
        add(obligatorio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 20, -1));

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 162, 30));

        ayuda.setForeground(new java.awt.Color(153, 153, 153));
        ayuda.setText("Los campos con * son obligatorios");
        add(ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        obligatorio3.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio3.setText(" *");
        add(obligatorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 10, -1));

        txt_nombres.setToolTipText("");
        txt_nombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombresKeyTyped(evt);
            }
        });
        add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 162, 30));

        txt_primerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_primerApellidoKeyTyped(evt);
            }
        });
        add(txt_primerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 162, 30));

        txt_segundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_segundoApellidoKeyTyped(evt);
            }
        });
        add(txt_segundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 162, 30));

        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });
        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });
        add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 162, 29));

        txt_numeroContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numeroContactoKeyTyped(evt);
            }
        });
        add(txt_numeroContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 162, 29));
        add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 360, 30));
        add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 360, 30));
        add(txt_repetirContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 360, 30));

        bx_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo de Usuario:", "Odontologo", "Auxiliar", "Cliente" }));
        add(bx_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, -1));

        obligatorio9.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio9.setText(" *");
        add(obligatorio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 10, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoFrui.jpg"))); // NOI18N
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crearActionPerformed
        nombre = txt_nombres.getText();
        apellido = txt_primerApellido.getText();
        cedula = txt_cedula.getText();
        correo = txt_correo.getText();
        numeroContacto = txt_numeroContacto.getText();
        apellid2 = txt_segundoApellido.getText(); //hrsgsrh
        pass = txt_contraseña.getText();
        repeatPass=txt_repetirContraseña.getText();
        usuario = txt_usuario.getText();
        direccion = txt_direccion.getText();
        tipoUsuario = bx_tipo_usuario.getSelectedItem().toString();

        if ((nombre.equals("Nombres")) || (pass.equals("Contraseña")) || (cedula.equals("Cédula"))
                || (correo.equals("Correo electronico (personal o empresarial)")) || (direccion.equals("Dirección domicilio")) || (numeroContacto.equals("Numero de contacto"))
                || (apellido.equals("Primer Apellido")) || (repeatPass.equals("Repita la Contraseña")) || (usuario.equals("Usuario"))
                || (bx_tipo_usuario.getSelectedItem().equals(""))) {
            
        } else if (!pass.equals(repeatPass) ) {
            System.out.println("contraseña errada");
        } else {
                logica.crearUsuario(nombre, apellido, cedula, correo, numeroContacto, apellid2, pass, usuario, direccion, tipoUsuario);
            }
            System.out.println("registro exitoso");
        this.txt_nombres.setText("Nombres");
        this.txt_cedula.setText("Cédula");
        this.txt_contraseña.setText("Contraseña");
        this.txt_numeroContacto.setText("Numero de contacto");
        this.txt_correo.setText("Correo electronico (personal o empresarial)");
        this.txt_direccion.setText("Dirección domicilio");
        this.txt_primerApellido.setText("Primer Apellido");
        this.txt_segundoApellido.setText("Segundo Apellido");
        this.txt_usuario.setText("Usuario");
        this.txt_repetirContraseña.setText("contraseña");
        
        
    }//GEN-LAST:event_boton_crearActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        
    }//GEN-LAST:event_boton_salirActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombresKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombresKeyTyped

    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_numeroContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroContactoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_numeroContactoKeyTyped

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void txt_primerApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_primerApellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_primerApellidoKeyTyped

    private void txt_segundoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_segundoApellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_segundoApellidoKeyTyped

    

    public void holders() {
        PlaceHolder holder;
        holder = new PlaceHolder(txt_nombres, "Nombres");
        holder = new PlaceHolder(txt_cedula, "Cédula");
        holder = new PlaceHolder(txt_contraseña, "Contraseña");
        holder = new PlaceHolder(txt_repetirContraseña, "Repita la Contraseña");
        holder = new PlaceHolder(txt_primerApellido, "Primer Apellido");
        holder = new PlaceHolder(txt_segundoApellido, "Segundo Apellido");
        holder = new PlaceHolder(txt_correo, "Correo electronico (personal o empresarial)");
        holder = new PlaceHolder(txt_direccion, "Dirección domicilio");
        holder = new PlaceHolder(txt_usuario, "Usuario");
        holder = new PlaceHolder(txt_numeroContacto, "Numero de contacto");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayuda;
    private javax.swing.JButton boton_crear;
    private javax.swing.JButton boton_salir;
    private javax.swing.JComboBox bx_tipo_usuario;
    private javax.swing.JLabel label_creandoUsuario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel obligatorio;
    private javax.swing.JLabel obligatorio1;
    private javax.swing.JLabel obligatorio2;
    private javax.swing.JLabel obligatorio3;
    private javax.swing.JLabel obligatorio4;
    private javax.swing.JLabel obligatorio5;
    private javax.swing.JLabel obligatorio6;
    private javax.swing.JLabel obligatorio7;
    private javax.swing.JLabel obligatorio8;
    private javax.swing.JLabel obligatorio9;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_numeroContacto;
    private javax.swing.JTextField txt_primerApellido;
    private javax.swing.JPasswordField txt_repetirContraseña;
    private javax.swing.JTextField txt_segundoApellido;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
